/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: DextonOfficial (https://sketchfab.com/DextonOfficial)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/apple-vision-pro-3341d1f3f75e41b59fcedd1f46f03d56
Title: Apple Vision Pro
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function VisionPro(props) {
  const { nodes, materials } = useGLTF('/apple_vision_pro.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" >
          <group name="root">
            <group name="GLTF_SceneRootNode" >
              <group
                name="scene_148"
                position={[0,0,0]}
                scale={0.03}>
                <group name="Meshes_147" scale={100}>
                  <group name="Sketchfab_model_146" >
                    <group name="USDRoot_145"  scale={0.02}>
                      <group name="tracking_node_placeholder_144">
                        <group name="VHXalTUGwQGLkJb_143">
                          <group name="OJENxduemLmPEam_142">
                            <group name="UzVAlGXcrjcgPuy_141">
                              <group name="QYiyPSizLHGUrqw_140">
                                <group name="hXmiHnglcDqNZLA_6">
                                  <group name="KDGFLTXqIYVblBJ_1">
                                    <mesh
                                      name="Object_14"
                                      castShadow
                                      receiveShadow
                                      geometry={nodes.Object_14.geometry}
                                      material={materials.FAJMtZQLswdvuhO}
                                    />
                                  </group>
                                  <group name="obpGPOxscQRBrFJ_2">
                                    <mesh
                                      name="Object_16"
                                      castShadow
                                      receiveShadow
                                      geometry={nodes.Object_16.geometry}
                                      material={materials.VxpiigirruNOshp}
                                    />
                                  </group>
                                  <group name="oSgdXMJmmhZQCzN_3">
                                    <mesh
                                      name="Object_18"
                                      castShadow
                                      receiveShadow
                                      geometry={nodes.Object_18.geometry}
                                      material={materials.FFhjkYvBaxmGeMa}
                                    />
                                  </group>
                                  <group name="SCIkocbuHjjNTsA_4">
                                    <mesh
                                      name="Object_20"
                                      castShadow
                                      receiveShadow
                                      geometry={nodes.Object_20.geometry}
                                      material={materials.ZwEHHHBVBsIGFLj}
                                    />
                                  </group>
                                  <group name="zzrLLSPyJZILSKY_0_5">
                                    <mesh
                                      name="Object_22"
                                      castShadow
                                      receiveShadow
                                      geometry={nodes.Object_22.geometry}
                                      material={materials.FFhjkYvBaxmGeMa}
                                    />
                                  </group>
                                </group>
                                <group name="ILTUsvoAEbTklIF_16">
                                  <group name="ASkoYyVECEcxkYK_0_7">
                                    <mesh
                                      name="Object_25"
                                      castShadow
                                      receiveShadow
                                      geometry={nodes.Object_25.geometry}
                                      material={materials.AjnVirXQeiPgFmd}
                                    />
                                  </group>
                                  <group name="EiAonKsxDEuXxGR_0_8">
                                    <mesh
                                      name="Object_27"
                                      castShadow
                                      receiveShadow
                                      geometry={nodes.Object_27.geometry}
                                      material={materials.xYIhbFReGzikXuj}
                                    />
                                  </group>
                                  <group name="IiAxItryhcbgzau_0_9">
                                    <mesh
                                      name="Object_29"
                                      castShadow
                                      receiveShadow
                                      geometry={nodes.Object_29.geometry}
                                      material={materials.FEdJjbtHQhrLkPc}
                                    />
                                  </group>
                                  <group name="IUxpbXmRrlbzURT_0_10">
                                    <mesh
                                      name="Object_31"
                                      castShadow
                                      receiveShadow
                                      geometry={nodes.Object_31.geometry}
                                      material={materials.msHgsHSWlHxyhfo}
                                    />
                                  </group>
                                  <group name="khLVByUFFaNMLSm_0_11">
                                    <mesh
                                      name="Object_33"
                                      castShadow
                                      receiveShadow
                                      geometry={nodes.Object_33.geometry}
                                      material={materials.TapGHbYtpjcGEyh}
                                    />
                                  </group>
                                  <group name="NIpSDFsUWUCOqdg_0_12">
                                    <mesh
                                      name="Object_35"
                                      castShadow
                                      receiveShadow
                                      geometry={nodes.Object_35.geometry}
                                      material={materials.XHmyiGBFGvanMAr}
                                    />
                                  </group>
                                  <group name="sfTtJVBhwbMtpKx_0_13">
                                    <mesh
                                      name="Object_37"
                                      castShadow
                                      receiveShadow
                                      geometry={nodes.Object_37.geometry}
                                      material={materials.GvidsfHBLmyLFLj}
                                    />
                                  </group>
                                  <group name="wMmLVLlxQNpoxwu_0_14">
                                    <mesh
                                      name="Object_39"
                                      castShadow
                                      receiveShadow
                                      geometry={nodes.Object_39.geometry}
                                      material={materials.gTQYGMoqLgKFhDN}
                                    />
                                  </group>
                                  <group name="ZpjYSYThqJeqGFZ_0_15">
                                    <mesh
                                      name="Object_41"
                                      castShadow
                                      receiveShadow
                                      geometry={nodes.Object_41.geometry}
                                      material={materials.XHmyiGBFGvanMAr}
                                    />
                                  </group>
                                </group>
                                <group name="nIENOhThDsFhBdC_49">
                                  <group name="DLPMBAQAjPpXjES_23">
                                    <group name="DesySQuVkxDlAlp_0_17">
                                      <mesh
                                        name="Object_45"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Object_45.geometry}
                                        material={materials.DesySQuVkxDlAlp_0}
                                      />
                                    </group>
                                    <group name="gRhjqEgpPdWDhFH_18">
                                      <mesh
                                        name="Object_47"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Object_47.geometry}
                                        material={materials.lagreFFLwlIcTJO}
                                      />
                                    </group>
                                    <group name="ltNMRLYerdBLGAz_19">
                                      <mesh
                                        name="Object_49"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Object_49.geometry}
                                        material={materials.uCIAdpMWlBjnYvL}
                                      />
                                    </group>
                                    <group name="SFnscRcMcAMgche_20">
                                      <mesh
                                        name="Object_51"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Object_51.geometry}
                                        material={materials.svovjBXowKlgbKD}
                                      />
                                    </group>
                                    <group name="swZapDaNVUxFTRq_21">
                                      <mesh
                                        name="Object_53"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Object_53.geometry}
                                        material={materials.svovjBXowKlgbKD}
                                      />
                                    </group>
                                    <group name="vxWoDJDXdJFnuSs_22">
                                      <mesh
                                        name="Object_55"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Object_55.geometry}
                                        material={materials.oRyqyBedXgltlyh}
                                      />
                                    </group>
                                  </group>
                                  <group name="HpwVpTrPEytuUsV_24">
                                    <mesh
                                      name="Object_57"
                                      castShadow
                                      receiveShadow
                                      geometry={nodes.Object_57.geometry}
                                      material={materials.LCFAOHKyQkTpEQF}
                                    />
                                  </group>
                                  <group name="IDbxuHOklZkAXLO_31">
                                    <group name="dcRUNTSwcozgcqO_25">
                                      <mesh
                                        name="Object_60"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Object_60.geometry}
                                        material={materials.svovjBXowKlgbKD}
                                      />
                                    </group>
                                    <group name="iweCqUsEZGYMjLj_26">
                                      <mesh
                                        name="Object_62"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Object_62.geometry}
                                        material={materials.svovjBXowKlgbKD}
                                      />
                                    </group>
                                    <group name="QWzDeiNdlTmLsaj_27">
                                      <mesh
                                        name="Object_64"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Object_64.geometry}
                                        material={materials.oRyqyBedXgltlyh}
                                      />
                                    </group>
                                    <group name="SqyAKiTAbYxFiMT_0_28">
                                      <mesh
                                        name="Object_66"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Object_66.geometry}
                                        material={materials.DesySQuVkxDlAlp_0}
                                      />
                                    </group>
                                    <group name="wBSkYahuvsEAlXg_29">
                                      <mesh
                                        name="Object_68"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Object_68.geometry}
                                        material={materials.lagreFFLwlIcTJO}
                                      />
                                    </group>
                                    <group name="yWGyQnAhCiOYRbg_30">
                                      <mesh
                                        name="Object_70"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Object_70.geometry}
                                        material={materials.uCIAdpMWlBjnYvL}
                                      />
                                    </group>
                                  </group>
                                  <group name="IXuJiiCFSNvsmGR_32">
                                    <mesh
                                      name="Object_72"
                                      castShadow
                                      receiveShadow
                                      geometry={nodes.Object_72.geometry}
                                      material={materials.dFHMyPBpPqeTjiL}
                                    />
                                  </group>
                                  <group name="jlIHzUMKnDyxeBA_33">
                                    <mesh
                                      name="Object_74"
                                      castShadow
                                      receiveShadow
                                      geometry={nodes.Object_74.geometry}
                                      material={materials.fBnoCDaWrdqLbCS}
                                    />
                                  </group>
                                  <group name="JOMymBNmrSzfzul_37">
                                    <group name="CJWfACsrSRGJXyf_34">
                                      <mesh
                                        name="Object_77"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Object_77.geometry}
                                        material={materials.QqwPOMufQnLHpVb}
                                      />
                                    </group>
                                    <group name="glyogFqKCZxZDOT_35">
                                      <mesh
                                        name="Object_79"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Object_79.geometry}
                                        material={materials.lagreFFLwlIcTJO}
                                      />
                                    </group>
                                    <group name="ZresYrVJWrzYduC_36">
                                      <mesh
                                        name="Object_81"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Object_81.geometry}
                                        material={materials.lagreFFLwlIcTJO}
                                      />
                                    </group>
                                  </group>
                                  <group name="OBrxMyeFLJpnKEt_44">
                                    <group name="AWbZOEfuRQAvVTP_38">
                                      <mesh
                                        name="Object_84"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Object_84.geometry}
                                        material={materials.XNhEODEcVemrRSu}
                                      />
                                    </group>
                                    <group name="DxrCMpAwhniUBfl_39">
                                      <mesh
                                        name="Object_86"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Object_86.geometry}
                                        material={materials.pMiARQLBeNgKOAx}
                                      />
                                    </group>
                                    <group name="IEooweRjLNVZPqx_40">
                                      <mesh
                                        name="Object_88"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Object_88.geometry}
                                        material={materials.NJTstBdwEqVPDBG}
                                      />
                                    </group>
                                    <group name="SRKTTAWIPJHVYpM_41">
                                      <mesh
                                        name="Object_90"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Object_90.geometry}
                                        material={materials.UvuKGGVdlOxVUeA}
                                      />
                                    </group>
                                    <group name="vIfAfiWawaJWGqD_42">
                                      <mesh
                                        name="Object_92"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Object_92.geometry}
                                        material={materials.pMiARQLBeNgKOAx}
                                      />
                                    </group>
                                    <group name="zOojMjLvernppMe_43">
                                      <mesh
                                        name="Object_94"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Object_94.geometry}
                                        material={materials.ySrzecxrjVirfze}
                                      />
                                    </group>
                                  </group>
                                  <group name="XiBfhExerhDKUWD_47">
                                    <group name="gCMrtHacMMbsVtY_45">
                                      <mesh
                                        name="Object_97"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Object_97.geometry}
                                        material={materials.hzzIZvnSVXHRIpk}
                                      />
                                    </group>
                                    <group name="yoKCFECQuCmdFPt_46">
                                      <mesh
                                        name="Object_99"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Object_99.geometry}
                                        material={materials.LrbPxjZrLaPVhbL}
                                      />
                                    </group>
                                  </group>
                                  <group name="YEoDlcPCcODxkbN_48">
                                    <mesh
                                      name="Object_101"
                                      castShadow
                                      receiveShadow
                                      geometry={nodes.Object_101.geometry}
                                      material={materials.JvGMyHWKpFKorez}
                                    />
                                  </group>
                                </group>
                                <group name="oUqvyVjpvXutbGz_65">
                                  <group name="CPVcQnPmdPluLLX_58">
                                    <group name="AGztyCyEbQgQICQ_51">
                                      <group name="NeorRpMRORinszX_50">
                                        <mesh
                                          name="Object_106"
                                          castShadow
                                          receiveShadow
                                          geometry={nodes.Object_106.geometry}
                                          material={materials.OcjoBBhHkqmGEeg}
                                        />
                                      </group>
                                    </group>
                                    <group name="cTCOfMLBXoYxhne_52">
                                      <mesh
                                        name="Object_108"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Object_108.geometry}
                                        material={materials.NHDhsOMHMgThpCN}
                                      />
                                    </group>
                                    <group name="EbXtcbKMemPvJWo_0_53">
                                      <mesh
                                        name="Object_110"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Object_110.geometry}
                                        material={materials.NHDhsOMHMgThpCN}
                                      />
                                    </group>
                                    <group name="MeGztcuEjPuJXZJ_54">
                                      <mesh
                                        name="Object_112"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Object_112.geometry}
                                        material={materials.gTQYGMoqLgKFhDN}
                                      />
                                    </group>
                                    <group name="tkgmgHsnFBmdriF_55">
                                      <mesh
                                        name="Object_114"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Object_114.geometry}
                                        material={materials.NLXCMSpYzHeRKCy}
                                      />
                                    </group>
                                    <group name="uLmdthzQafdZhtY_56">
                                      <mesh
                                        name="Object_116"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Object_116.geometry}
                                        material={materials.HjiVKkmzDRBQwcd}
                                      />
                                    </group>
                                    <group name="YloUIBCKBFoZsyn_57">
                                      <mesh
                                        name="Object_118"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Object_118.geometry}
                                        material={materials.nirjontYTAixgEJ}
                                      />
                                    </group>
                                  </group>
                                  <group name="CqBFBePJMWkWMeo_64">
                                    <group name="EiWAFcSpgUbRfLC_59">
                                      <mesh
                                        name="Object_121"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Object_121.geometry}
                                        material={materials.HjiVKkmzDRBQwcd}
                                      />
                                    </group>
                                    <group name="LttGJckIvzcXqfr_60">
                                      <mesh
                                        name="Object_123"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Object_123.geometry}
                                        material={materials.nirjontYTAixgEJ}
                                      />
                                    </group>
                                    <group name="tNyidXzsanoTPLC_61">
                                      <mesh
                                        name="Object_125"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Object_125.geometry}
                                        material={materials.NLXCMSpYzHeRKCy}
                                      />
                                    </group>
                                    <group name="ttGMShCisdkbKAx_0_62">
                                      <mesh
                                        name="Object_127"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Object_127.geometry}
                                        material={materials.NHDhsOMHMgThpCN}
                                      />
                                    </group>
                                    <group name="xyBlAAQKYgueyAl_63">
                                      <mesh
                                        name="Object_129"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Object_129.geometry}
                                        material={materials.gTQYGMoqLgKFhDN}
                                      />
                                    </group>
                                  </group>
                                </group>
                                <group name="UnACEWcnmbGfHlv_139">
                                  <group name="KnuTzhAOmSULOMY_138">
                                    <group name="cqDpjysIDbeaHGW_69">
                                      <group name="cTBEkXCWkvHrohb_66">
                                        <mesh
                                          name="Object_134"
                                          castShadow
                                          receiveShadow
                                          geometry={nodes.Object_134.geometry}
                                          material={materials.LlnrRvRtBSKKJtZ}
                                        />
                                      </group>
                                      <group name="jmyvTSbhlLzcdVy_67">
                                        <mesh
                                          name="Object_136"
                                          castShadow
                                          receiveShadow
                                          geometry={nodes.Object_136.geometry}
                                          material={materials.IUXXlUlgvhvFPzz}
                                        />
                                      </group>
                                      <group name="vyzuKbgYqRUloHN_68">
                                        <mesh
                                          name="Object_138"
                                          castShadow
                                          receiveShadow
                                          geometry={nodes.Object_138.geometry}
                                          material={materials.gFHmZYZAcTzegfV}
                                        />
                                      </group>
                                    </group>
                                    <group name="dQauJkamRIzUDkH_73">
                                      <group name="BYzAzdYRSKOXgvW_70">
                                        <mesh
                                          name="Object_141"
                                          castShadow
                                          receiveShadow
                                          geometry={nodes.Object_141.geometry}
                                          material={materials.gFHmZYZAcTzegfV}
                                        />
                                      </group>
                                      <group name="COzyZGNXWoVuulX_71">
                                        <mesh
                                          name="Object_143"
                                          castShadow
                                          receiveShadow
                                          geometry={nodes.Object_143.geometry}
                                          material={materials.LlnrRvRtBSKKJtZ}
                                        />
                                      </group>
                                      <group name="txsLdslKWGeEPTt_72">
                                        <mesh
                                          name="Object_145"
                                          castShadow
                                          receiveShadow
                                          geometry={nodes.Object_145.geometry}
                                          material={materials.IUXXlUlgvhvFPzz}
                                        />
                                      </group>
                                    </group>
                                    <group name="ebhwPuFAweGgfLf_86">
                                      <group name="BDnAUbPNZRAcuFf_0_74">
                                        <mesh
                                          name="Object_148"
                                          castShadow
                                          receiveShadow
                                          geometry={nodes.Object_148.geometry}
                                          material={materials.RWqkxBAMyYvCfAW}
                                        />
                                      </group>
                                      <group name="exuyFScfUaBPCtN_77">
                                        <group name="aTcrhiBFDpmfQRb_75">
                                          <mesh
                                            name="Object_151"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Object_151.geometry}
                                            material={materials.kPwwriYXUEalYIj}
                                          />
                                        </group>
                                        <group name="gqNMwQGbnhvlVYE_76">
                                          <mesh
                                            name="Object_153"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Object_153.geometry}
                                            material={materials.lZazJJAwgeaFFzW}
                                          />
                                        </group>
                                      </group>
                                      <group name="gImAVESIoCwjazi_78">
                                        <mesh
                                          name="Object_155"
                                          castShadow
                                          receiveShadow
                                          geometry={nodes.Object_155.geometry}
                                          material={materials.lZazJJAwgeaFFzW}
                                        />
                                      </group>
                                      <group name="hciIxHvmXHAqkAZ_0_79">
                                        <mesh
                                          name="Object_157"
                                          castShadow
                                          receiveShadow
                                          geometry={nodes.Object_157.geometry}
                                          material={materials.CzTcyZGBTOTEuIC}
                                        />
                                      </group>
                                      <group name="iKgldARsoOWlIms_81">
                                        <group name="npnXECWbsAmgBIA_80">
                                          <mesh
                                            name="Object_160"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Object_160.geometry}
                                            material={materials.CzTcyZGBTOTEuIC}
                                          />
                                        </group>
                                      </group>
                                      <group name="IVshDKAKUOpgoit_0_82">
                                        <mesh
                                          name="Object_162"
                                          castShadow
                                          receiveShadow
                                          geometry={nodes.Object_162.geometry}
                                          material={materials.hQMaJbjPDPOUdry}
                                        />
                                      </group>
                                      <group name="jZNSaLYonRzXGgY_0_83">
                                        <mesh
                                          name="Object_164"
                                          castShadow
                                          receiveShadow
                                          geometry={nodes.Object_164.geometry}
                                          material={materials.lZazJJAwgeaFFzW}
                                        />
                                      </group>
                                      <group name="syRtTlwvwBGbycm_0_84">
                                        <mesh
                                          name="Object_166"
                                          castShadow
                                          receiveShadow
                                          geometry={nodes.Object_166.geometry}
                                          material={materials.lZazJJAwgeaFFzW}
                                        />
                                      </group>
                                      <group name="xpJqyjMVpSjpaIw_85">
                                        <mesh
                                          name="Object_168"
                                          castShadow
                                          receiveShadow
                                          geometry={nodes.Object_168.geometry}
                                          material={materials.CzTcyZGBTOTEuIC}
                                        />
                                      </group>
                                    </group>
                                    <group name="jjJIZDrSILBzxpu_87">
                                      <mesh
                                        name="Object_170"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Object_170.geometry}
                                        material={materials.CzTcyZGBTOTEuIC}
                                      />
                                    </group>
                                    <group name="mVSPBjPnCvaDnYB_89">
                                      <group name="lntlgnzyayryFPp_0_88">
                                        <mesh
                                          name="Object_173"
                                          castShadow
                                          receiveShadow
                                          geometry={nodes.Object_173.geometry}
                                          material={materials.WicotZnvNvRZKUL}
                                        />
                                      </group>
                                    </group>
                                    <group name="sAgjMlMZDvwGuaG_95">
                                      <group name="GlqEjTaipLhaVeX_90">
                                        <mesh
                                          name="Object_176"
                                          castShadow
                                          receiveShadow
                                          geometry={nodes.Object_176.geometry}
                                          material={materials.sWxIuDoQFWtTiiB}
                                        />
                                      </group>
                                      <group name="MZFwKssnShOZpjd_94">
                                        <group name="PelEjfQtfCcokND_91">
                                          <mesh
                                            name="Object_179"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Object_179.geometry}
                                            material={materials.hjAUwLwBADKDzhk}
                                          />
                                        </group>
                                        <group name="utXOMjnivVWqOqb_92">
                                          <mesh
                                            name="Object_181"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Object_181.geometry}
                                            material={materials.GevKBvqYjYnmUWP}
                                          />
                                        </group>
                                        <group name="UXLjllnBycNoaYM_0_93">
                                          <mesh
                                            name="Object_183"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Object_183.geometry}
                                            material={materials.FOugkDgsmvxAjLB}
                                          />
                                        </group>
                                      </group>
                                    </group>
                                    <group name="sdZTCdioMLSEJyx_99">
                                      <group name="AxIDAohNCLUnqHZ_0_96">
                                        <mesh
                                          name="Object_186"
                                          castShadow
                                          receiveShadow
                                          geometry={nodes.Object_186.geometry}
                                          material={materials.svoioOWqcyuDHRV}
                                        />
                                      </group>
                                      <group name="gyYovHxVbMYfNIs_0_97">
                                        <mesh
                                          name="Object_188"
                                          castShadow
                                          receiveShadow
                                          geometry={nodes.Object_188.geometry}
                                          material={materials.CzTcyZGBTOTEuIC}
                                        />
                                      </group>
                                      <group name="sPvEwoSuAuchoUX_98">
                                        <mesh
                                          name="Object_190"
                                          castShadow
                                          receiveShadow
                                          geometry={nodes.Object_190.geometry}
                                          material={materials.HAvYQJgmRpVYpqr}
                                        />
                                      </group>
                                    </group>
                                    <group name="SWQhQzMpkCoHddc_102">
                                      <group name="EohuhBblivKlgiW_100">
                                        <mesh
                                          name="Object_193"
                                          castShadow
                                          receiveShadow
                                          geometry={nodes.Object_193.geometry}
                                          material={materials.CzTcyZGBTOTEuIC}
                                        />
                                      </group>
                                      <group name="zvEZknZipHczcSh_101">
                                        <mesh
                                          name="Object_195"
                                          castShadow
                                          receiveShadow
                                          geometry={nodes.Object_195.geometry}
                                          material={materials.snsykSygkWSDIlk}
                                        />
                                      </group>
                                    </group>
                                    <group name="ueCvCVRqPVTUdjQ_134">
                                      <group name="iWNovCLKqGktbvq_128">
                                        <group name="bBsMtAxpDKIOtGt_113">
                                          <group name="bWGTZHjKQZbtiyV_103">
                                            <mesh
                                              name="Object_200"
                                              castShadow
                                              receiveShadow
                                              geometry={nodes.Object_200.geometry}
                                              material={materials.svoioOWqcyuDHRV}
                                            />
                                          </group>
                                          <group name="ddBlCIbantllDIr_104">
                                            <mesh
                                              name="Object_202"
                                              castShadow
                                              receiveShadow
                                              geometry={nodes.Object_202.geometry}
                                              material={materials.kEEsgKvKWifaKeg}
                                            />
                                          </group>
                                          <group name="fAUXGIjKanMeYea_105">
                                            <mesh
                                              name="Object_204"
                                              castShadow
                                              receiveShadow
                                              geometry={nodes.Object_204.geometry}
                                              material={materials.svoioOWqcyuDHRV}
                                            />
                                          </group>
                                          <group name="GCtZYOQqcgvnxPi_106">
                                            <mesh
                                              name="Object_206"
                                              castShadow
                                              receiveShadow
                                              geometry={nodes.Object_206.geometry}
                                              material={materials.kEEsgKvKWifaKeg}
                                            />
                                          </group>
                                          <group name="GqNvIoTBBTlyOqi_0_107">
                                            <mesh
                                              name="Object_208"
                                              castShadow
                                              receiveShadow
                                              geometry={nodes.Object_208.geometry}
                                              material={materials.NLAQCwOxsrAPIlV}
                                            />
                                          </group>
                                          <group name="ItWUvMBTKMADVpz_108">
                                            <mesh
                                              name="Object_210"
                                              castShadow
                                              receiveShadow
                                              geometry={nodes.Object_210.geometry}
                                              material={materials.kEEsgKvKWifaKeg}
                                            />
                                          </group>
                                          <group name="jEXLbqFcYStQaQF_109">
                                            <mesh
                                              name="Object_212"
                                              castShadow
                                              receiveShadow
                                              geometry={nodes.Object_212.geometry}
                                              material={materials.svoioOWqcyuDHRV}
                                            />
                                          </group>
                                          <group name="MeigMDdpfMwthLL_110">
                                            <mesh
                                              name="Object_214"
                                              castShadow
                                              receiveShadow
                                              geometry={nodes.Object_214.geometry}
                                              material={materials.svoioOWqcyuDHRV}
                                            />
                                          </group>
                                          <group name="nrLqYYObKenvfDT_111">
                                            <mesh
                                              name="Object_216"
                                              castShadow
                                              receiveShadow
                                              geometry={nodes.Object_216.geometry}
                                              material={materials.nctcFIvFhZfKDLQ}
                                            />
                                          </group>
                                          <group name="wPwRzjPYjmrlEXX_112">
                                            <mesh
                                              name="Object_218"
                                              castShadow
                                              receiveShadow
                                              geometry={nodes.Object_218.geometry}
                                              material={materials.kEEsgKvKWifaKeg}
                                            />
                                          </group>
                                        </group>
                                        <group name="KYYFwKltpNVwIZF_114">
                                          <mesh
                                            name="Object_220"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Object_220.geometry}
                                            material={materials.GevKBvqYjYnmUWP}
                                          />
                                        </group>
                                        <group name="PCWXKVLQMLFXuiB_115">
                                          <mesh
                                            name="Object_222"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Object_222.geometry}
                                            material={materials.CzTcyZGBTOTEuIC}
                                          />
                                        </group>
                                        <group name="VbBsIFpjSsioAOC_126">
                                          <group name="HsgHlwEylVMvWpH_116">
                                            <mesh
                                              name="Object_225"
                                              castShadow
                                              receiveShadow
                                              geometry={nodes.Object_225.geometry}
                                              material={materials.kEEsgKvKWifaKeg}
                                            />
                                          </group>
                                          <group name="hXjngMziGWeRsLG_117">
                                            <mesh
                                              name="Object_227"
                                              castShadow
                                              receiveShadow
                                              geometry={nodes.Object_227.geometry}
                                              material={materials.kEEsgKvKWifaKeg}
                                            />
                                          </group>
                                          <group name="JlZUAmaWBjQdvyx_118">
                                            <mesh
                                              name="Object_229"
                                              castShadow
                                              receiveShadow
                                              geometry={nodes.Object_229.geometry}
                                              material={materials.nctcFIvFhZfKDLQ}
                                            />
                                          </group>
                                          <group name="kpOufxRkGzbfIDK_119">
                                            <mesh
                                              name="Object_231"
                                              castShadow
                                              receiveShadow
                                              geometry={nodes.Object_231.geometry}
                                              material={materials.svoioOWqcyuDHRV}
                                            />
                                          </group>
                                          <group name="loKnjuoUUqCXjyh_120">
                                            <mesh
                                              name="Object_233"
                                              castShadow
                                              receiveShadow
                                              geometry={nodes.Object_233.geometry}
                                              material={materials.kEEsgKvKWifaKeg}
                                            />
                                          </group>
                                          <group name="LRMIvaRwBWdAizA_0_121">
                                            <mesh
                                              name="Object_235"
                                              castShadow
                                              receiveShadow
                                              geometry={nodes.Object_235.geometry}
                                              material={materials.NLAQCwOxsrAPIlV}
                                            />
                                          </group>
                                          <group name="mYnwxJZquqykmUm_122">
                                            <mesh
                                              name="Object_237"
                                              castShadow
                                              receiveShadow
                                              geometry={nodes.Object_237.geometry}
                                              material={materials.kEEsgKvKWifaKeg}
                                            />
                                          </group>
                                          <group name="RNQzvxThOUKSCWj_123">
                                            <mesh
                                              name="Object_239"
                                              castShadow
                                              receiveShadow
                                              geometry={nodes.Object_239.geometry}
                                              material={materials.svoioOWqcyuDHRV}
                                            />
                                          </group>
                                          <group name="vJNXctsYfhEHtrV_124">
                                            <mesh
                                              name="Object_241"
                                              castShadow
                                              receiveShadow
                                              geometry={nodes.Object_241.geometry}
                                              material={materials.svoioOWqcyuDHRV}
                                            />
                                          </group>
                                          <group name="XyedbPFDxeHwCHk_125">
                                            <mesh
                                              name="Object_243"
                                              castShadow
                                              receiveShadow
                                              geometry={nodes.Object_243.geometry}
                                              material={materials.svoioOWqcyuDHRV}
                                            />
                                          </group>
                                        </group>
                                        <group name="wNTsFMcHtcwMFzu_0_127">
                                          <mesh
                                            name="Object_245"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Object_245.geometry}
                                            material={materials.hjAUwLwBADKDzhk}
                                          />
                                        </group>
                                      </group>
                                      <group name="KoNEaPeZscsdFdt_132">
                                        <group name="KFVogPQUiddsMSf_129">
                                          <mesh
                                            name="Object_248"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Object_248.geometry}
                                            material={materials.CzTcyZGBTOTEuIC}
                                          />
                                        </group>
                                        <group name="MspSzkAWtrSNgSu_0_130">
                                          <mesh
                                            name="Object_250"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Object_250.geometry}
                                            material={materials.GevKBvqYjYnmUWP}
                                          />
                                        </group>
                                        <group name="ZMUGAWqZYOylVJZ_131">
                                          <mesh
                                            name="Object_252"
                                            castShadow
                                            receiveShadow
                                            geometry={nodes.Object_252.geometry}
                                            material={materials.hjAUwLwBADKDzhk}
                                          />
                                        </group>
                                      </group>
                                      <group name="NnqtZkGomSmVeRm_0_133">
                                        <mesh
                                          name="Object_254"
                                          castShadow
                                          receiveShadow
                                          geometry={nodes.Object_254.geometry}
                                          material={materials.hjAUwLwBADKDzhk}
                                        />
                                      </group>
                                    </group>
                                    <group name="zpoQgybStAEjzdB_137">
                                      <group name="DxigZplXoWuQGiB_135">
                                        <mesh
                                          name="Object_257"
                                          castShadow
                                          receiveShadow
                                          geometry={nodes.Object_257.geometry}
                                          material={materials.snsykSygkWSDIlk}
                                        />
                                      </group>
                                      <group name="TDKyRfvojNkpooB_136">
                                        <mesh
                                          name="Object_259"
                                          castShadow
                                          receiveShadow
                                          geometry={nodes.Object_259.geometry}
                                          material={materials.CzTcyZGBTOTEuIC}
                                        />
                                      </group>
                                    </group>
                                  </group>
                                </group>
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/apple_vision_pro.glb')
